# Generated by Django 5.2.4 on 2025-07-30 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nfctags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFCTaggedItem',
        ),
        migrations.AlterModelOptions(
            name='nfctag',
            options={},
        ),
        migrations.RemoveField(
            model_name='nfctag',
            name='metadata',
        ),
        migrations.AddField(
            model_name='nfctag',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='nfctag',
            index=models.Index(fields=['content_type', 'object_id'], name='nfctags_nfc_content_3226d3_idx'),
        ),
    ]
