# Generated by Django 6.0.2 on 2026-04-19 02:18

from django.db import migrations, models


def cleanup_legacy_gbif_id(apps, schema_editor):
    """Convert legacy gbif_id=6 (Kingdom Plantae default) to NULL.

    gbif_id=6 was used as a stand-in default when no real GBIF species was
    assigned. It references Kingdom Plantae, not an actual species. Any plant
    still carrying this value should have a NULL gbif_id instead.
    """
    Plant = apps.get_model("botany", "Plant")
    Plant.objects.filter(gbif_id=6).update(gbif_id=None)


def reverse_cleanup_legacy_gbif_id(apps, schema_editor):
    """Restore NULL gbif_id values to 6 (original legacy default) on rollback."""
    Plant = apps.get_model("botany", "Plant")
    Plant.objects.filter(gbif_id__isnull=True).update(gbif_id=6)


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='The date this plant was acquired.', null=True, verbose_name='acquisition date'),
        ),
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(blank=True, help_text="Where this plant is kept (e.g. 'Living room').", max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-form notes about this plant.', verbose_name='notes'),
        ),
        # AlterField must precede RunPython so the column accepts NULL
        # before the data migration attempts to write NULL values.
        migrations.AlterField(
            model_name='plant',
            name='gbif_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='The GBIF ID of the plant.', null=True, verbose_name='GBIF ID'),
        ),
        migrations.RunPython(
            cleanup_legacy_gbif_id,
            reverse_code=reverse_cleanup_legacy_gbif_id,
        ),
    ]
