# Generated by Django 5.2.4 on 2025-07-23 08:12

import django.db.models.deletion
import nfctags.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botany', '0001_initial'),
        ('nfctags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('uid', models.CharField(db_index=True, editable=False, max_length=32, unique=True, validators=[nfctags.validators.validate_ascii_mirror_uid])),
                ('metadata', models.JSONField(default=dict, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, default='Plant Label', help_text='The title of the plant label.', max_length=255, verbose_name='title')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'plant label',
                'verbose_name_plural': 'plant labels',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaggedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfctag', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='nfctags.nfctag')),
                ('plant', models.ForeignKey(help_text='The plant associated with this tag.', on_delete=django.db.models.deletion.CASCADE, related_name='tagged_plants', to='botany.plant', verbose_name='plant')),
            ],
            options={
                'verbose_name': 'tagged plant',
                'verbose_name_plural': 'tagged plants',
            },
        ),
    ]
