# Generated by Django 5.2.4 on 2025-07-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantlabel',
            name='metadata',
        ),
        migrations.AddField(
            model_name='plantlabel',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='plantlabel',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='TaggedPlant',
        ),
    ]
