# Generated by Django 6.0.2 on 2026-04-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botany", "0001_initial"),
        ("domain", "0003_remove_plantlabel_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantlabel",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="The plant this NFC label is bound to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nfc_labels",
                to="botany.plant",
                verbose_name="plant",
            ),
        ),
    ]
